petercinibulk/envied

- packages/envied/lib/src/envied_base.dart
- packages/envied/test/envy_test.dart
- packages/envied_generator/lib/src/generate_line_encrypted.dart
- packages/envied_generator/lib/src/generator.dart
- packages/envied_generator/test/src/generator_tests.dart
Since `envify` seems to have been abandoned and @techouse pointed me to this project, I will offer you my obfuscation option also here :)
For reference: https://github.com/frencojobs/envify/pull/28
> feat: Add obfuscation option

- README.md
I updated the readme to remove the confusion caused by `envName`.
Addresses https://github.com/petercinibulk/envied/issues/5 and https://github.com/petercinibulk/envied/issues/7
> docs: Update readme by replacing envName with varName

- packages/envied/README.md
I updated the README to remove the confusion caused by envName.
caused by 199fdfbc79b1f113f47940eb3717559c192632d9
related this #5
> docs: replace envName with varName in README

- packages/envied/pubspec.yaml
- packages/envied_generator/pubspec.yaml
* [CHORE] bump Dart SDK to ">=2.19.0 <4.0.0"
* [FIX] downgrade analyzer to ^5.11.1 
* [FIX] downgrade lints to ^2.0.0
- fixes https://github.com/petercinibulk/envied/issues/32
- `lints: ^2.1.0` requires Dart 3.0.0
> fix: amend dependencies and bump Dart SDK to ">=2.19.0 <4.0.0"

- examples/envied_example/.env
- examples/envied_example/.env_debug
- examples/envied_example/lib/app_env.dart
- examples/envied_example/lib/app_env_fields.dart
- examples/envied_example/lib/debug_env.dart
- examples/envied_example/lib/debug_env.g.dart
- examples/envied_example/lib/env.dart
- examples/envied_example/lib/env.g.dart
- examples/envied_example/lib/release_env.dart
- examples/envied_example/lib/release_env.g.dart
- examples/envied_example/pubspec.lock
- examples/envied_example/pubspec.yaml
- packages/envied/lib/src/envied_base.dart
- packages/envied/pubspec.yaml
- packages/envied_generator/lib/builder.dart
- packages/envied_generator/lib/src/generate_line.dart
- packages/envied_generator/lib/src/generate_line_encrypted.dart
- packages/envied_generator/lib/src/generator.dart
- packages/envied_generator/lib/src/load_envs.dart
- packages/envied_generator/lib/src/parser.dart
- packages/envied_generator/pubspec.yaml
- packages/envied_generator/test/src/generator_tests.dart
- pubspec.lock
- pubspec.yaml
- bump the version to `0.4.0`
- raise Dart SDK minimum to 3.0.0
- update dependencies (except analyzer)
- add a `const` constructor to the `EnviedGenerator`
- add the [final Dart 3 class modifier](https://dart.dev/language/class-modifiers#final) `Envied`, `EnviedField`, `EnviedGenerator` and `Parser`
- declare all the `Parser` methods as `static`
- refactor the generator by:
- adding explicit types
- explicitly declaring nested functions
- converting all immutable `var` variables to `final`
- generate all `_Env` classes with the [final Dart 3 class modifier](https://dart.dev/language/class-modifiers#final), i.e.
```dart
final class _Env16 {
static const String testDefaultParam = 'test_';
}
```
- update example
> refactor: facelift both Envied and EnviedGenerator to Dart 3.0

- packages/envied_generator/pubspec.yaml
Since more and more packages are gonna bump their analyzer to v6, I thought it would be wise to gracefully update the version using
```yaml
analyzer: ">=5.1.0 <7.0.0"
```
This won't break older apps and will allow newer ones to use the package without any issues.
> chore: allow usage of analyzer v6

- .github/workflows/main.yml
- .github/workflows/publish.yml
- .github/workflows/publish_dry_run.yml
- .github/workflows/test.yml
Addresses #51
I have made the `main.yml` workflow reusable and used it as a test job upon which the publish job depends.
1. a `pull_request` of a branch named `release/*` will trigger a dry run
2. a `push` will trigger a deployment if the tags match this pattern:
- `'envied-v[0-9]+.[0-9]+.[0-9]+*'`
- `'envied_generator-v[0-9]+.[0-9]+.[0-9]+*'`
I didn't use melos here as I saw no need and because melos uses `dart pub publish` [under the hood anyway](https://melos.invertase.dev/guides/automated-releases#publishing).
I have left a comment for you in the workflow where you will have to create an environment with the name `pub.dev` (or you can name it differently) just as it's outlined here in [this guide](https://dart.dev/tools/pub/automated-publishing#configuring-automated-publishing-from-git …
> chore: add release workflow

- .github/workflows/publish.yml
Added
```yaml
on:
push:
tags:
- 'v[0-9]+.[0-9]+.[0-9]+*'
```
so that a tag like that can also trigger a release.
Additionally I added the check
```yaml
- name: Compare version with ref/tag
id: compare_version_with_tag
run: |
set -e
TAG=${GITHUB_REF_NAME#v}
if [[ "$VERSION" != "$TAG" ]]; then
echo "Version in ${{ matrix.package }}/pubspec.yaml ($VERSION) does not match tag ($TAG)"
echo "Skipping publish for ${{ matrix.package }}"
echo "SHOULD_RUN=0" >> $GITHUB_ENV
else
echo "SHOULD_RUN=1" >> $GITHUB_ENV
fi
```
> chore: fix publish CI

- packages/envied/README.md
- packages/envied_generator/lib/src/generate_field_encrypted.dart
- packages/envied_generator/test/.env.example
- packages/envied_generator/test/src/generator_tests.dart
Please merge #70 first. Then I will mark this draft as ready :)
I ultimately decided against the IEEE 754 approach since the user needs to specify the `double` as a string anyway.
This way, it was very easy to simultaneously add `double` and `num` support.
Fixes #71
> feat: Obfuscated `double`s and `num`s

- packages/envied_generator/test/.env.example
- packages/envied_generator/test/src/generator_tests.dart
Added additional tests for:
This will raise the current coverage from 93.45% to **96.6%**.
> chore: add more tests

- .github/workflows/publish.yml
- .github/workflows/test.yml
Update [actions/checkout](https://github.com/actions/checkout) to v4 (was v3)
> chore: update actions/checkout to v4 (was v3)

- CHANGELOG.md
- packages/envied/CHANGELOG.md
- packages/envied/pubspec.yaml
- packages/envied_generator/CHANGELOG.md
- packages/envied_generator/pubspec.yaml
---
- [`envied` - `v0.5.2`](#envied---v052)
- [`envied_generator` - `v0.5.2`](#enviedgenerator---v052)
---
- **FEAT**: add ability to convert field name from camelCase to CONSTANT_CASE (#42)
- **FEAT**: add ability to convert field name from camelCase to CONSTANT_CASE (#42)
- **FEAT**: generated files are now ignored in the coverage report (#62)
- **FEAT**: add support for Uri fields (#70)
- **FEAT**: add support for DateTime fields (#70)
- **FEAT**: add support for obfuscated double fields (#72)
- **FEAT**: add support for obfuscated num fields (#72)
- **FEAT**: add support for enum fields (#73)
> chore: release v0.5.2

- .github/workflows/publish.yml
I noticed that [softprops/action-gh-release](https://github.com/softprops/action-gh-release) is [overwriting](https://github.com/petercinibulk/envied/actions/runs/6916291046/job/18816230176#step:13:16) a [previous](https://github.com/petercinibulk/envied/actions/runs/6916291046/job/18816230091#step:13:15) Girthub Release with the same tag because I forgot to explicitly add a `tag_name`. 🙈
> fix: prevent Github Release from overwriting a release with the same tag

- examples/envied_example/pubspec.lock
- examples/envied_example/pubspec.yaml
- packages/envied_generator/lib/src/generate_field_encrypted.dart
- packages/envied_generator/pubspec.yaml
I did some refactoring on the generator
I also bumped the dependencies in the example.
> refactor: generator

- CHANGELOG.md
- packages/envied/CHANGELOG.md
- packages/envied/pubspec.yaml
- packages/envied_generator/CHANGELOG.md
- packages/envied_generator/pubspec.yaml
---
- [`envied` - `v0.5.3`](#envied---v053)
- [`envied_generator` - `v0.5.3`](#enviedgenerator---v053)
---
- **FEAT**: optional path build.yaml option (#83)
- **CHORE**: update readme regarding #6 (#79)
- **FEAT**: optional path build.yaml option (#83)
- **REFACTOR**: replace `Code` blocks with dedicated `Expression.operatorBitwiseXor` (#81)
- **REFACTOR**: use `TypeReference` instead of raw `refer` for `List`s (#81)
> chore: release v0.5.3

- examples/envied_example/pubspec.lock
- packages/envied/README.md
- packages/envied/lib/src/envied_base.dart
I've added simplified version on annotation with default options.
Instead of writing this:
`@Envied()`
Now we can write this as well:
`@envied`
Same convention is used in [@freezed](https://github.com/rrousselGit/freezed/blob/e61af260968b5762792a0a2e0016bdb3ccf0df23/packages/freezed_annotation/lib/freezed_annotation.dart#L497) or [@riverpod](https://github.com/rrousselGit/riverpod/blob/5c853b424cacf4774c81ccec688c3345f97edae7/packages/riverpod_annotation/lib/src/riverpod_annotation.dart#L106)
> feat: add @envied annotation with default options

- CHANGELOG.md
- examples/envied_example/pubspec.lock
- packages/envied/CHANGELOG.md
- packages/envied/pubspec.yaml
- packages/envied_generator/CHANGELOG.md
- packages/envied_generator/pubspec.yaml
---
- [`envied` - `v0.5.4`](#envied---v054)
- [`envied_generator` - `v0.5.4`](#enviedgenerator---v054)
---
- **FEAT**: add support for raw strings and no interpolation (#95)
- **FEAT**: add @envied annotation with default options (#92)
- **FEAT**: add support for raw strings and no interpolation (#95)
> chore: release v0.5.4

- CHANGELOG.md
- packages/envied/CHANGELOG.md
- packages/envied/pubspec.yaml
- packages/envied_generator/CHANGELOG.md
- packages/envied_generator/pubspec.yaml
---
- [`envied` - `v0.5.4+1`](#envied---v0541)
- [`envied_generator` - `v0.5.4+1`](#enviedgenerator---v0541)
---
- **FIX**: fix parsing lines with multiple equal signs (#100)
- **FIX**: fix parsing lines with multiple equal signs (#100)
> chore: release v0.5.4+1

- packages/envied/CHANGELOG.md
- packages/envied/lib/src/envied_base.dart
- packages/envied/test/envy_test.dart
- packages/envied_generator/CHANGELOG.md
- packages/envied_generator/lib/src/generate_field_encrypted.dart
- packages/envied_generator/lib/src/generator.dart
Hello!
I'm using the obfuscate feature from clean builds in CI/CD, but every build is generating different output, so checks that I have for unchanged autogenerated files are failing.
My proposed solution is to provide optionally a seed for the random number generator.
> feat: add support to custom random seed

- examples/envied_example/CHANGELOG.md
- examples/envied_example/pubspec.yaml
- melos.yaml
- packages/envied/CHANGELOG.md
- packages/envied/pubspec.yaml
- packages/envied_generator/CHANGELOG.md
- packages/envied_generator/pubspec.yaml
---
- [`envied` - `v1.0.0`](#envied---v100)
- [`envied_generator` - `v1.0.0`](#enviedgenerator---v100)
---
- **FEAT**: add support for custom seed when using Random during the obfuscation. (#116)
- **FEAT**: add support for custom seed when using Random during the obfuscation. (#116)
> chore: release v1.0.0

- examples/envied_example/pubspec.lock
- packages/envied/CHANGELOG.md
- packages/envied/pubspec.yaml
- packages/envied_generator/CHANGELOG.md
- packages/envied_generator/pubspec.yaml
---
- [`envied` - `v1.0.1`](#envied---v101)
- [`envied_generator` - `v1.0.1`](#enviedgenerator---v101)
---
- **FEAT**: multiple generations for same class (#124)
- **FEAT**: allow reading System env key from .env files (#120)
- **FEAT**: multiple generations for same class (#124)
- **FEAT**: allow reading System env key from .env files (#120)
> chore: release v1.0.1

- examples/envied_example/pubspec.lock
- packages/envied_generator/lib/src/generator.dart
- packages/envied_generator/pubspec.yaml
- packages/envied_generator/test/src/generator_tests.dart
A mock Dependabot PR that supersedes #128.
---
These dependencies need to be updated together.
Bumps [analyzer](https://github.com/dart-lang/sdk/tree/main/pkg/analyzer) from >=5.1.0 <7.0.0 to 7.1.0.
Bumps [dart_style](https://github.com/dart-lang/dart_style) from  2.3.2 to 3.0.1.
- [Release notes](https://github.com/dart-lang/dart_style/releases)
- [Commits](https://github.com/dart-lang/dart_style/compare/v2.3.2...v3.0.1)
Bumps [source_gen](https://github.com/dart-lang/source_gen) from 1.5.0 to 2.0.0.
- [Release notes](https://github.com/dart-lang/source_gen/releases)
- [Commits](https://github.com/dart-lang/source_gen/compare/source_gen-v1.5.0...source_gen-v2.0.0)
---
updated-dependencies:
- dependency-name: analyzer
dependency-type: direct:production
update-type: …
> chore(deps)!: bump analyzer, source_gen, drop redundant dart_style in /packages/envied_generator

- examples/envied_example/analysis_options.yaml
- examples/envied_example/lib/app_env.dart
- examples/envied_example/lib/envs.env.dart
- examples/envied_example/lib/envs.env.g.dart
- examples/envied_example/lib/example.dart
- packages/envied_generator/lib/src/generate_field.dart
- packages/envied_generator/lib/src/generate_field_encrypted.dart
- packages/envied_generator/lib/src/generator.dart
- packages/envied_generator/test/src/generator_tests.dart
This pull request includes several changes to the `envied_example` and `envied_generator` packages to improve type safety, add support for multiple annotations, and update the generated code structure. The most important changes include modifying the `AppEnv` and `Envs` classes, updating the `generateFields` and `generateFieldsEncrypted` functions, and enhancing the `EnviedGenerator` class to handle multiple annotations.
* [`examples/envied_example/lib/app_env.dart`](diffhunk://#diff-eb6fc84a6085143dc7ba473385a8a214fa5c3ac3ba9de80469df7bdaa79dfbcbL10-R10): Changed `kDebugMode` to explicitly use `bool` type.
* [`examples/envied_example/lib/envs.env.dart`](diffhunk://#diff-358efa9199d705c949c43991ef125addcf944dc48f20375cd0302a323565d3daL26-R30): Updated `kDebugMode` to explicitly use `bool` …
> fix: multiple generations for same class

- packages/envied/README.md
Hi! 👋 😄 
This PR addresses that issue https://github.com/petercinibulk/envied/issues/139#issuecomment-2664747950.
So the lack of information in README that user has to set `override` parameter to true in `build.yaml` in order to say `envied` that it should use path given in CLI e.g.
```shell
dart run build_runner build --define=envied_generator:envied=path=my_other.env
```
Without setting `override` parameter, `envied` sticks to the default `.env` path.
> docs: add mention about `override` parameter when setting path through CLI

- packages/envied/README.md
This pull request includes several updates to the `packages/envied/README.md` file to improve clarity and add new content. The most important changes include updating headings for consistency, adding a section on handling multiple environments, and making minor formatting adjustments.
Updates to headings and sections:
* Updated the heading for optional environment variables to remove unnecessary emphasis.
* Updated the heading for environment variable naming conventions to remove unnecessary emphasis.
* Updated the heading for build configuration overrides to remove unnecessary emphasis.
New content and examples:
* Added a new section on handling multiple environments, including an example of how to use different `.env` files for debug and production environments.
Minor formatting …
> docs: improve README formatting and add multiple environments section

- CHANGELOG.md
- packages/envied/CHANGELOG.md
- packages/envied/pubspec.yaml
- packages/envied_generator/CHANGELOG.md
- packages/envied_generator/pubspec.yaml
- pubspec.yaml
---
- [`envied` - `v1.2.0`](#envied---v120)
- [`envied_generator` - `v1.2.0`](#enviedgenerator---v120)
---
- **CHORE**: migrate to analyzer Element2 model (#151)
- **CHORE**: migrate to analyzer Element2 model (#151)
> chore: release v1.2.0

- CHANGELOG.md
- packages/envied/CHANGELOG.md
- packages/envied/pubspec.yaml
- packages/envied_generator/CHANGELOG.md
- packages/envied_generator/pubspec.yaml
This pull request updates both the `envied` and `envied_generator` packages to version `1.2.1`, focusing on dependency maintenance. The main change is relaxing the version constraint for the `analyzer` dependency to support newer versions, ensuring compatibility with the latest analyzer releases.
Dependency updates:
* Updated the `analyzer` dependency constraint to `>=7.4.0 <9.0.0` in both `envied` and `envied_generator` packages (`pubspec.yaml` files). [[1]](diffhunk://#diff-0ab64f02a4548fe7b0b2ec6930cb927fb8d736ede8a22bb0694d71bef993baacL3-R3) [[2]](diffhunk://#diff-acb232fc5faa8303647cace24c98bffa46bbdc289002a3d6b1de5c73b1061212L3-R3)
* Documented the dependency update in the changelogs for both packages (`CHANGELOG.md`). [[1]](diffhunk://#diff-fd735a2acf953a6047d6f30cf168e707ff8c08610c …
> chore: release v1.2.1

- CHANGELOG.md
- packages/envied/CHANGELOG.md
- packages/envied/pubspec.yaml
- packages/envied_generator/CHANGELOG.md
- packages/envied_generator/pubspec.yaml
This pull request updates both the `envied` and `envied_generator` packages to version 1.3.0, focusing on broadening the version constraints for their `build` and `source_gen` dependencies to improve compatibility with newer versions. There are no breaking changes in this release.
Dependency updates:
* Broadened version constraints for the `build` and `source_gen` dependencies in both `envied` and `envied_generator` to allow for greater flexibility and compatibility with future versions.
Version bump and changelog:
* Bumped the version of `envied` and `envied_generator` to 1.3.0 in their respective `pubspec.yaml` files and added corresponding entries to their `CHANGELOG.md` files. [[1]](diffhunk://#diff-0ab64f02a4548fe7b0b2ec6930cb927fb8d736ede8a22bb0694d71bef993baacL3-R3) …
> chore: release v1.3.0

- packages/envied/lib/src/envied_base.dart
The import is unnecessary as far as I can tell.
In fact, removing this single import should mark `envied` as compatible with Web - because I was wondering why it should not be compatible with Web (after reading #161)
> chore: remove `dart:io` from envied
